#!/bin/sh

die() {
	echo "$0: [fatal] $1" >&2;
	exit 2;
}
usage() {
	echo "Usage: $0 configdir storedir" >&2;
	exit 1;
}
configfail() {
	die "Can't read config file: $1";
}

if test $# -lt "2"; then usage; fi;
configdir="$1";
store="$2";

url=$(cat "$configdir/url") || configfail "mirror URL";
arch=$(cat "$configdir/packagearch") || configfail "package machine architecture";
repos=$(cat "$configdir/repos") || configfail "repository list";

cd "$store" || die "cd to store directory failed";
echo "--- Local directory: ${store}";
echo "--- rsync prefix: ${url}";
# honour max delete limit from official mirrors
export ARCH_MIRROR_LIMITDELETE=1;

for repo in $repos; do {
	component="${repo}/os/${arch}"
	remote="${url}/${component}/";
	# note we're currently cd'd into the local store dir.
	local="./${component}/";
	# create directory if it doesn't exist for first run
	mkdir -p "$local" || die "local directory creation for repo $repo failed";
	echo "--- Syncing repo $repo: ${remote} -> ${local}";
	arch-mirror-rsync "$remote" "$local";
}; done;
