#!/bin/sh

# borrowed from sysexits.h
EX_USAGE=64;
EX_CONFIG=78;
EX_OSERROR=71;
EX_OSFILE=72;

pathfail() {
	echo "Failed to load configuration file: $1 ($2)" >&2;
	exit $EX_CONFIG;
}

updatefail() {
	echo "Updating configuration failed: $1 ($2)" >&2;
	exit $EX_OSFILE;
}

if test $# -lt 2; then echo "Usage: $0 interface network" >&2; exit $EX_USAGE; fi;
interface="$1";
network="$2";

# we need to know where nftfirewall stores the runtime configuration directory.
paths="/etc/nftfirewall/paths";
runtimeconf="$paths/runtimeconf";
runtimedir=$(cat "$runtimeconf") || pathfail "nftfirewall runtime path file" "$runtimeconf";

profiledir="/etc/wpa.conf.d/network-profiles";
# find the profile to use for this network, abort if not found
echo "Looking for firewall profile for network $network";
path="$profiledir/$network";

profile=$(cat "$path") || pathfail "profile selector for network $network" "$path"

# assign profile for interface and try to apply firewall changes
echo "Network profile detected: \"$profile\"";
path="$runtimedir/profiles/$interface";
echo "Updating nftfirewall profile selector $path";
echo "$profile" > "$path" || updatefail "interface profile selector" "$path";
exec nftfirewall || { echo "nftfirewall invocation failed!" >&2; exit $EX_OSERROR; };
