#!/bin/sh
printf %s "username: " >&2;
read -r username;
printf %s "domain: " >&2;
read -r domain;
printf %s "password: " >&2;

stty -echo;
read -r password;
stty echo;

echo "username=$username";
echo "domain=$domain";
echo "password=$password";
