#!/bin/sh
mirror="$1";
repo="$2";

if test -z "${mirror}"; then echo "missing Rsync URL"; exit 1; fi
if test -z "${repo}"; then echo "missing repository name"; exit 1; fi

arch="x86_64";
component="${repo}/os/${arch}/";
url="${mirror}${component}";
echo "--- ${repo}: ${url}";
local="./${component}";
#temporary="$PWD/temp/${component}";
mkdir -p "${local}" || exit 1;

rsync --recursive --times --links --hard-links --delete-after --update --copy-links --safe-links --max-delete=1000 --delete-excluded --exclude='.*' "${url}" "${local}";
